/**
 * scrape-programs.ts — degree/program requirements for KS.
 *
 * Auto-generated by scripts/lib/discover-programs.ts. Each entry maps a
 * college slug to the catalog platform discovered for that college. Edit
 * configs (catoid, catalogYear, programNavoids, etc.) per the platform
 * template's options interface before relying on the data.
 *
 * Usage:
 *   npx tsx scripts/ks/scrape-programs.ts
 */

import * as fs from "fs";
import * as path from "path";
import { applyProgramMatching } from "../../lib/programs/matcher.js";
import { scrapeAcalogPrograms } from "../lib/scrape-acalog-programs.js";
import { scrapeCourseleafPrograms } from "../lib/scrape-courseleaf-programs.js";
import { scrapeCoursedogPrograms } from "../lib/scrape-coursedog-programs.js";

async function run(
  slug: string,
  scrape: () => Promise<{ programs: unknown[]; catalog_year: string; catalog_url: string; college_slug: string; scraped_at: string }>,
): Promise<void> {
  console.log(`\n=== ${slug} ===`);
  try {
    const data = await scrape();
    if (data.programs.length === 0) {
      console.log(`  No programs found for ${slug}.`);
      return;
    }
    const { matched, unmatched } = applyProgramMatching(data.programs as never);
    console.log(`  Matcher: ${matched} matched / ${unmatched} unmatched`);
    const outDir = path.join(process.cwd(), "data", "ks", "programs");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(data, null, 2));
    console.log(`  ✓ Wrote ${data.programs.length} programs → ${outPath}`);
  } catch (e) {
    console.error(`  ✗ ${slug} failed: ${e}`);
  }
}

async function main() {
  console.log("KS program scraper");
  // coffeyville-community-college (acalog)
  await run("coffeyville-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "coffeyville-community-college", baseUrl: "https://catalog.coffeyville.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // cowley-county-community-college (acalog)
  await run("cowley-county-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "cowley-county-community-college", baseUrl: "https://catalog.cowley.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // neosho-county-community-college (acalog)
  await run("neosho-county-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "neosho-county-community-college", baseUrl: "https://catalog.neosho.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // highland-community-college (courseleaf)
  await run("highland-community-college", () =>
    scrapeCourseleafPrograms({ collegeSlug: "highland-community-college", baseUrl: "https://catalog.highland.edu" }),
  );

  // manhattan-area-technical-college (courseleaf)
  await run("manhattan-area-technical-college", () =>
    scrapeCourseleafPrograms({ collegeSlug: "manhattan-area-technical-college", baseUrl: "https://catalog.manhattan.edu" }),
  );

  // pratt-community-college (coursedog)
  await run("pratt-community-college", () =>
    scrapeCoursedogPrograms({ collegeSlug: "pratt-community-college", catalogDomain: "catalog.pratt.edu", catalogYear: "" }),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
