import { getAllStates } from "@/lib/states/registry";
import { loadInstitutions } from "@/lib/institutions";
import { getCurrentTerm } from "@/lib/terms";
import { getCollegeLastUpdated } from "@/lib/data-freshness";
import {
  toSitemapXml,
  siteOrigin,
  xmlResponse,
  type SitemapEntry,
} from "@/lib/sitemap-xml";
// Pre-built per-(state, college, term) subject-count rollup. The previous
// implementation looped `loadCoursesForCollege` over ~675 colleges during
// static generation; each call did a Supabase COUNT + paginated section
// fetch. Run with `staticGenerationMaxConcurrency: 1` × 3 workers on
// Vercel, the parallel queries blew through the free-tier connection pool
// and Vercel's 60s per-page static-gen budget — surfacing as dozens of
// "loadCoursesForCollege count error:" lines followed by
// "Failed to build /sitemap/college-subjects.xml/route after 3 attempts."
// The snapshot is regenerated by `npm run build:sitemap-data-snapshot`
// on every deploy from the same on-disk JSON files the scrape → import
// pipeline writes, so it matches what Supabase has.
import snapshotJson from "@/data/sitemap-college-subjects.json";

const SUBJECT_SNAPSHOT: Record<string, Array<{ prefix: string; count: number }>> =
  (snapshotJson as unknown as Record<string, Array<{ prefix: string; count: number }>>) ?? {};

const MIN_SECTIONS_FOR_INDEXED_URL = 5;

export const dynamic = "force-dynamic";

export async function GET() {
  const url = siteOrigin();
  const entries: SitemapEntry[] = [];

  for (const state of getAllStates()) {
    // getCurrentTerm reads the small term-counts snapshot synchronously
    // when available (lib/terms.ts), so even at 51 states this is
    // microseconds of work — no Supabase round-trips here.
    let currentTerm: string;
    try {
      currentTerm = await getCurrentTerm(state.slug);
    } catch {
      continue;
    }
    if (!currentTerm) continue;

    for (const inst of loadInstitutions(state.slug)) {
      const key = `${state.slug}|${inst.college_slug}|${currentTerm}`;
      const prefixes = SUBJECT_SNAPSHOT[key];
      if (!prefixes) continue;
      for (const { prefix, count } of prefixes) {
        if (count < MIN_SECTIONS_FOR_INDEXED_URL) continue;
        entries.push({
          url: `${url}/${state.slug}/college/${inst.id}/courses/${prefix.toLowerCase()}`,
          changeFrequency: "weekly",
          priority: 0.5,
          lastModified:
            getCollegeLastUpdated(state.slug, inst.college_slug) ?? undefined,
        });
      }
    }
  }

  return xmlResponse(toSitemapXml(entries));
}
