// AUTO-GENERATED 2026-06-17 from Google Search Console.
// These blog posts earned ZERO clicks in BOTH the pre-collapse window
// (2026-04-20..05-10) and the current window (2026-05-25..06-12). The
// May 2026 Google core update read the 136-post blog cluster as 'scaled
// programmatic content' and demoted it from avg position ~9 to ~37; the
// cluster drove ~19 clicks total in 3 weeks before, 0 after. We noindex
// (follow:true) the 128 non-performers
// so they no longer drag the domain's sitewide quality signal, while the
// 8 posts that did earn clicks stay indexed. follow:true keeps internal
// links live so link equity still flows. To re-index a post that rebounds,
// remove its slug here. Posts NOT listed (incl. future posts) index normally.
// Regenerate: see /tmp/gen_noindex.py (GSC-driven).
export const BLOG_NOINDEX_SLUGS: ReadonlySet<string> = new Set([
  "alabama-community-college-course-availability",
  "alabama-community-college-hybrid-density",
  "alabama-community-college-late-start-classes",
  "blue-ridge-community-college-audit-class-guide",
  "brightpoint-community-college-audit-class-guide",
  "california-community-college-course-availability",
  "california-transfer-receivers-compared",
  "camp-paul-d-camp-community-college-audit-class-guide",
  "central-virginia-community-college-audit-class-guide",
  "colorado-community-college-course-availability",
  "community-college-course-codes-explained",
  "community-college-sessions-explained",
  "comparing-transfer-credit-across-states",
  "comparing-transfer-credit-across-universities",
  "connecticut-community-college-prereq-bottlenecks",
  "connecticut-ct-state-unified-system-guide",
  "connecticut-senior-citizens-ct-state-tuition-waiver",
  "connecticut-state-community-college-session-timing-guide",
  "danville-community-college-audit-class-guide",
  "dc-senior-citizens-udc-community-college",
  "delaware-community-college-late-start-classes",
  "delaware-community-college-transfer-credit-guide",
  "delaware-technical-community-college-prereq-bottlenecks",
  "district-of-columbia-community-college-late-start-classes",
  "district-of-columbia-community-college-prereq-bottlenecks",
  "florida-community-college-course-availability",
  "florida-community-college-late-start-classes",
  "florida-community-college-prereq-bottlenecks",
  "florida-community-college-session-timing-guide",
  "florida-community-college-transfer-credit-guide",
  "florida-senior-citizens-fcs-tuition-waiver",
  "georgia-community-college-course-availability",
  "georgia-community-college-late-start-classes",
  "georgia-community-college-prereq-bottlenecks",
  "georgia-senior-citizens-tcsg-tuition-waiver",
  "georgia-technical-college-session-timing-guide",
  "georgia-transfer-receivers-compared",
  "germanna-community-college-audit-class-guide",
  "how-to-build-community-college-schedule",
  "how-to-check-if-community-college-course-transfers",
  "how-to-find-late-start-community-college-classes",
  "how-to-read-transfer-equivalency-table",
  "hybrid-community-college-classes-explained",
  "indiana-community-college-hybrid-density",
  "kentucky-community-college-course-availability",
  "kentucky-community-college-hybrid-density",
  "kentucky-community-college-late-start-classes",
  "last-day-to-add-drop-community-college-class",
  "maine-community-college-hybrid-density",
  "maine-transfer-receivers-compared",
  "maryland-community-college-hybrid-density",
  "maryland-community-college-late-start-classes",
  "maryland-community-college-prereq-bottlenecks",
  "maryland-community-college-session-timing-guide",
  "maryland-community-college-transfer-credit-guide",
  "maryland-senior-citizens-community-college-tuition-waiver",
  "maryland-transfer-receivers-compared",
  "massachusetts-community-college-hybrid-density",
  "massachusetts-community-college-late-start-classes",
  "massachusetts-community-college-prereq-bottlenecks",
  "massachusetts-community-college-session-timing-guide",
  "massachusetts-community-college-transfer-credit-guide",
  "massachusetts-senior-citizens-community-college-tuition-waiver",
  "michigan-community-college-prereq-bottlenecks",
  "mississippi-community-college-late-start-classes",
  "new-hampshire-ccsnh-transfer-credit-guide",
  "new-hampshire-community-college-late-start-classes",
  "new-hampshire-community-college-prereq-bottlenecks",
  "new-jersey-community-college-prereq-bottlenecks",
  "new-jersey-community-college-transfer-credit-guide",
  "new-jersey-transfer-receivers-compared",
  "new-york-community-college-hybrid-density",
  "new-york-cuny-community-college-prereq-bottlenecks",
  "new-york-cuny-community-college-session-timing-guide",
  "new-york-cuny-community-college-transfer-guide",
  "new-york-cuny-senior-citizens-tuition-waiver",
  "new-york-transfer-receivers-compared",
  "north-carolina-community-college-course-availability",
  "north-carolina-community-college-hybrid-density",
  "north-carolina-community-college-late-start-classes",
  "north-carolina-community-college-prereq-bottlenecks",
  "north-carolina-community-college-session-timing-guide",
  "north-carolina-transfer-guides-how-to-use",
  "north-carolina-transfer-receivers-compared",
  "nova-northern-virginia-community-college-audit-class-guide",
  "ohio-community-college-prereq-bottlenecks",
  "online-vs-in-person-community-college-classes",
  "pennsylvania-community-college-prereq-bottlenecks",
  "pennsylvania-community-college-transfer-credit-guide",
  "pennsylvania-senior-citizens-community-college-tuition-waiver",
  "prerequisite-chains-why-four-semester-plans-take-six",
  "reynolds-community-college-audit-class-guide",
  "rhode-island-community-college-late-start-classes",
  "rhode-island-community-college-prereq-bottlenecks",
  "senior-citizen-community-college-tuition-all-15-states",
  "south-carolina-community-college-hybrid-density",
  "south-carolina-technical-college-course-availability",
  "south-carolina-technical-college-late-start-classes",
  "south-carolina-technical-college-prereq-bottlenecks",
  "south-carolina-technical-college-session-timing-guide",
  "south-carolina-technical-college-transfer",
  "south-dakota-community-college-hybrid-density",
  "taking-classes-at-multiple-community-colleges",
  "tcc-tidewater-community-college-audit-class-guide",
  "tennessee-community-college-course-availability",
  "tennessee-community-college-late-start-classes",
  "tennessee-community-college-prereq-bottlenecks",
  "tennessee-community-college-session-timing-guide",
  "tennessee-senior-citizens-tbr-community-colleges",
  "tennessee-tbr-community-college-transfer-guide",
  "texas-community-college-course-availability",
  "vermont-community-college-late-start-classes",
  "vermont-community-college-prereq-bottlenecks",
  "virginia-community-college-course-availability",
  "virginia-community-college-hybrid-density",
  "virginia-community-college-prereq-bottlenecks",
  "virginia-community-college-session-timing-guide",
  "virginia-senior-citizens-community-college-free-tuition",
  "washington-community-college-hybrid-density",
  "washington-community-college-late-start-classes",
  "what-direct-match-vs-elective-credit-means",
  "what-does-audit-a-class-mean",
  "what-is-bio-101-danville-community-college",
  "what-is-exsc-240-frederick-community-college",
  "what-is-sdv-100-danville-community-college",
  "when-do-community-college-schedules-go-live",
  "which-community-college-courses-are-hard-to-find",
  "which-universities-are-toughest-transfer-receivers",
]);

export function isBlogNoindexed(slug: string): boolean {
  return BLOG_NOINDEX_SLUGS.has(slug);
}
