import termCountsSnapshot from "../data/term-counts.json";
import { getAvailableTerms } from "./courses";
import { supabase } from "./supabase";
import { termLabel, termSortKey } from "./term-label";

// Re-export pure helpers so existing `@/lib/terms` imports keep working.
// New client-only callers should import directly from `@/lib/term-label` to
// avoid pulling Supabase + fs into the client bundle.
export { termLabel, termSortKey };

// ---------------------------------------------------------------------------
// In-memory cache (shared with courses.ts pattern)
// ---------------------------------------------------------------------------

const CACHE_TTL = 5 * 60 * 1000; // 5 minutes

interface CacheEntry<T> {
  data: T;
  expires: number;
}

const cache = new Map<string, CacheEntry<unknown>>();
const inflight = new Map<string, Promise<unknown>>();

async function cached<T>(key: string, fn: () => Promise<T>): Promise<T> {
  const entry = cache.get(key) as CacheEntry<T> | undefined;
  if (entry && entry.expires > Date.now()) return entry.data;

  // Deduplicate concurrent requests for the same key
  const existing = inflight.get(key) as Promise<T> | undefined;
  if (existing) return existing;

  const promise = fn()
    .then((data) => {
      cache.set(key, { data, expires: Date.now() + CACHE_TTL });
      inflight.delete(key);
      return data;
    })
    .catch((err) => {
      inflight.delete(key);
      throw err;
    });

  inflight.set(key, promise);
  return promise;
}

/**
 * Get all available terms with labels, sorted newest first.
 */
export async function getAvailableTermsForDisplay(state: string): Promise<{
  code: string;
  label: string;
}[]> {
  const terms = await getAvailableTerms(state);
  return terms
    .map((code) => ({ code, label: termLabel(code) }))
    .sort((a, b) => termSortKey(b.code) - termSortKey(a.code));
}

// ---------------------------------------------------------------------------
// Batch current-term resolver
//
// During Next.js static generation, dozens of pages call getCurrentTerm() for
// different states concurrently. Next runs ~3 worker processes, each with its
// own in-memory cache — so without coordination they all fire the same
// expensive RPC against a 1M+-row courses table at the same time. Combined
// with stale visibility-map between vacuums, the Index Only Scan falls back
// to heap fetches and the 2-minute statement_timeout kills the query.
//
// Fix: static-import a pre-built snapshot from data/term-counts.json
// (generated by scripts/build-term-counts-snapshot.ts in the npm build
// pipeline, then inlined by the bundler). Zero DB calls during static
// gen, no per-process cold misses, and works in edge runtime — no fs/path
// imports that would break edge bundling.
//
// Snapshot is committed-in and rebuilt every deploy from data/{state}/
// courses/, so freshness tracks deploys. That's the granularity that
// matters here: the "current term" only changes when the underlying
// per-college course files do.
//
// The RPC fallback is preserved for the edge case where the snapshot is
// missing or empty (e.g., a checkout before npm run build:term-counts-
// snapshot has ever run, or tests that bypass the build pipeline).
// ---------------------------------------------------------------------------

interface TermCountRow {
  state: string;
  term: string;
  college_count: number;
}

// Approximate first month of each season (0-indexed). Used by isWithinHorizon
// to compare a term code against the calendar — we don't need exact academic
// dates, just a roughly-correct month so the horizon filter rejects terms
// unambiguously too far out.
const SEASON_MONTH: Record<string, number> = { SP: 1, SU: 5, FA: 8 };

/**
 * True when `term` is no more than `monthsAhead` months in the future from
 * `now`. Past terms always pass — we keep them so a state whose scrape only
 * has stale data still resolves to *something* useful instead of falling
 * through to the hardcoded default.
 *
 * Exported for unit tests.
 */
export function isWithinHorizon(
  term: string,
  monthsAhead = 9,
  now: Date = new Date(),
): boolean {
  const m = term.match(/^(\d{4})(SP|SU|FA)$/);
  if (!m) return true; // unknown format — don't reject
  const termDate = new Date(parseInt(m[1]), SEASON_MONTH[m[2]], 1);
  const monthDelta =
    (termDate.getFullYear() - now.getFullYear()) * 12 +
    (termDate.getMonth() - now.getMonth());
  return monthDelta <= monthsAhead;
}

/**
 * Pick the term that best represents "what students should see right now"
 * for a state. Prefers terms with the most college coverage; on ties,
 * prefers the more recent term.
 *
 * Horizon filter (added 2026-06-01): drop terms more than ~9 months in the
 * future before the tie-break. Without it, a state with few colleges (NH,
 * CT, UT, AR, NV — all 1–3 colleges) where every scraped term has
 * college_count=1 would let a stray 2027SU scrape beat a well-populated
 * 2026FA on the recency tie-break — and the API would serve a tiny set of
 * future-term sections as "current," making search look broken on prod.
 * Concrete case: NH had 2026SP=21, 2026SU=10, 2026FA=35, 2027SP=22,
 * 2027SU=9 sections, all college_count=1 — pickBestTerm returned 2027SU.
 *
 * If the horizon filter empties the pool (state has *only* far-future data
 * — e.g. an incomplete scrape), fall back to the unfiltered list so we
 * still return a real term.
 *
 * Exported for unit tests.
 */
export function pickBestTerm(
  rows: TermCountRow[],
  now: Date = new Date(),
): string {
  if (rows.length === 0) return "2026SP";
  const inHorizon = rows.filter((r) => isWithinHorizon(r.term, 9, now));
  const pool = inHorizon.length > 0 ? inHorizon : rows;

  let bestTerm = pool[0].term;
  let bestCount = Number(pool[0].college_count);
  for (const row of pool) {
    const count = Number(row.college_count);
    if (
      count > bestCount ||
      (count === bestCount && termSortKey(row.term) > termSortKey(bestTerm))
    ) {
      bestTerm = row.term;
      bestCount = count;
    }
  }
  return bestTerm;
}

async function loadAllCurrentTerms(): Promise<Map<string, string>> {
  // Prefer the statically-imported snapshot. Production builds always
  // populate it; the RPC fallback only fires if the snapshot is missing
  // or empty (rare — e.g. fresh checkout, or test environment).
  let rows: TermCountRow[] =
    Array.isArray(termCountsSnapshot) && termCountsSnapshot.length > 0
      ? (termCountsSnapshot as TermCountRow[])
      : [];

  if (rows.length === 0) {
    const { data, error } = await supabase.rpc("get_all_term_college_counts");
    if (error || !data) {
      console.warn(
        "get_all_term_college_counts RPC error:",
        error?.message ?? error,
      );
      return new Map();
    }
    rows = data as TermCountRow[];
  }

  const byState = new Map<string, TermCountRow[]>();
  for (const row of rows) {
    if (!byState.has(row.state)) byState.set(row.state, []);
    byState.get(row.state)!.push(row);
  }

  const result = new Map<string, string>();
  for (const [st, stateRows] of byState) {
    result.set(st, pickBestTerm(stateRows));
  }
  return result;
}

/**
 * Get the current term code by querying Supabase.
 * Batch-fetches all states' term→college counts in one RPC call, then caches
 * the map. Returns the term with the most college data, breaking ties by recency.
 * Falls back to "2026SP" if no data is found.
 */
export async function getCurrentTerm(state: string): Promise<string> {
  return cached(`currentTerm:${state}`, async () => {
    const allTerms = await cached("currentTermMap:all", loadAllCurrentTerms);
    return allTerms.get(state) ?? "2026SP";
  });
}

/**
 * Get the next term after the latest one we have data for.
 * SP → SU → FA → next year SP
 */
export async function getNextTerm(state: string): Promise<{ code: string; label: string }> {
  const current = await getCurrentTerm(state);
  const match = current.match(/^(\d{4})(SP|SU|FA)$/);
  if (!match) return { code: "2026FA", label: "Fall 2026" };

  const year = parseInt(match[1]);
  const season = match[2];

  let nextCode: string;
  if (season === "SP") nextCode = `${year}SU`;
  else if (season === "SU") nextCode = `${year}FA`;
  else nextCode = `${year + 1}SP`;

  return { code: nextCode, label: termLabel(nextCode) };
}
