import termCountsSnapshot from "../data/term-counts.json";
import { getAvailableTerms } from "./courses";
import { supabase } from "./supabase";
import { termLabel, termSortKey } from "./term-label";

// Re-export pure helpers so existing `@/lib/terms` imports keep working.
// New client-only callers should import directly from `@/lib/term-label` to
// avoid pulling Supabase + fs into the client bundle.
export { termLabel, termSortKey };

// ---------------------------------------------------------------------------
// In-memory cache (shared with courses.ts pattern)
// ---------------------------------------------------------------------------

const CACHE_TTL = 5 * 60 * 1000; // 5 minutes

interface CacheEntry<T> {
  data: T;
  expires: number;
}

const cache = new Map<string, CacheEntry<unknown>>();
const inflight = new Map<string, Promise<unknown>>();

async function cached<T>(key: string, fn: () => Promise<T>): Promise<T> {
  const entry = cache.get(key) as CacheEntry<T> | undefined;
  if (entry && entry.expires > Date.now()) return entry.data;

  // Deduplicate concurrent requests for the same key
  const existing = inflight.get(key) as Promise<T> | undefined;
  if (existing) return existing;

  const promise = fn()
    .then((data) => {
      cache.set(key, { data, expires: Date.now() + CACHE_TTL });
      inflight.delete(key);
      return data;
    })
    .catch((err) => {
      inflight.delete(key);
      throw err;
    });

  inflight.set(key, promise);
  return promise;
}

/**
 * Get all available terms with labels, sorted newest first.
 */
export async function getAvailableTermsForDisplay(state: string): Promise<{
  code: string;
  label: string;
}[]> {
  const terms = await getAvailableTerms(state);
  return terms
    .map((code) => ({ code, label: termLabel(code) }))
    .sort((a, b) => termSortKey(b.code) - termSortKey(a.code));
}

// ---------------------------------------------------------------------------
// Batch current-term resolver
//
// During Next.js static generation, dozens of pages call getCurrentTerm() for
// different states concurrently. Next runs ~3 worker processes, each with its
// own in-memory cache — so without coordination they all fire the same
// expensive RPC against a 1M+-row courses table at the same time. Combined
// with stale visibility-map between vacuums, the Index Only Scan falls back
// to heap fetches and the 2-minute statement_timeout kills the query.
//
// Fix: static-import a pre-built snapshot from data/term-counts.json
// (generated by scripts/build-term-counts-snapshot.ts in the npm build
// pipeline, then inlined by the bundler). Zero DB calls during static
// gen, no per-process cold misses, and works in edge runtime — no fs/path
// imports that would break edge bundling.
//
// Snapshot is committed-in and rebuilt every deploy from data/{state}/
// courses/, so freshness tracks deploys. That's the granularity that
// matters here: the "current term" only changes when the underlying
// per-college course files do.
//
// The RPC fallback is preserved for the edge case where the snapshot is
// missing or empty (e.g., a checkout before npm run build:term-counts-
// snapshot has ever run, or tests that bypass the build pipeline).
// ---------------------------------------------------------------------------

interface TermCountRow {
  state: string;
  term: string;
  college_count: number;
}

function pickBestTerm(rows: TermCountRow[]): string {
  if (rows.length === 0) return "2026SP";
  let bestTerm = rows[0].term;
  let bestCount = Number(rows[0].college_count);
  for (const row of rows) {
    const count = Number(row.college_count);
    if (
      count > bestCount ||
      (count === bestCount && termSortKey(row.term) > termSortKey(bestTerm))
    ) {
      bestTerm = row.term;
      bestCount = count;
    }
  }
  return bestTerm;
}

async function loadAllCurrentTerms(): Promise<Map<string, string>> {
  // Prefer the statically-imported snapshot. Production builds always
  // populate it; the RPC fallback only fires if the snapshot is missing
  // or empty (rare — e.g. fresh checkout, or test environment).
  let rows: TermCountRow[] =
    Array.isArray(termCountsSnapshot) && termCountsSnapshot.length > 0
      ? (termCountsSnapshot as TermCountRow[])
      : [];

  if (rows.length === 0) {
    const { data, error } = await supabase.rpc("get_all_term_college_counts");
    if (error || !data) {
      console.warn(
        "get_all_term_college_counts RPC error:",
        error?.message ?? error,
      );
      return new Map();
    }
    rows = data as TermCountRow[];
  }

  const byState = new Map<string, TermCountRow[]>();
  for (const row of rows) {
    if (!byState.has(row.state)) byState.set(row.state, []);
    byState.get(row.state)!.push(row);
  }

  const result = new Map<string, string>();
  for (const [st, stateRows] of byState) {
    result.set(st, pickBestTerm(stateRows));
  }
  return result;
}

/**
 * Get the current term code by querying Supabase.
 * Batch-fetches all states' term→college counts in one RPC call, then caches
 * the map. Returns the term with the most college data, breaking ties by recency.
 * Falls back to "2026SP" if no data is found.
 */
export async function getCurrentTerm(state: string): Promise<string> {
  return cached(`currentTerm:${state}`, async () => {
    const allTerms = await cached("currentTermMap:all", loadAllCurrentTerms);
    return allTerms.get(state) ?? "2026SP";
  });
}

/**
 * Get the next term after the latest one we have data for.
 * SP → SU → FA → next year SP
 */
export async function getNextTerm(state: string): Promise<{ code: string; label: string }> {
  const current = await getCurrentTerm(state);
  const match = current.match(/^(\d{4})(SP|SU|FA)$/);
  if (!match) return { code: "2026FA", label: "Fall 2026" };

  const year = parseInt(match[1]);
  const season = match[2];

  let nextCode: string;
  if (season === "SP") nextCode = `${year}SU`;
  else if (season === "SU") nextCode = `${year}FA`;
  else nextCode = `${year + 1}SP`;

  return { code: nextCode, label: termLabel(nextCode) };
}
