/**
 * scrape-programs.ts — degree/program requirements for LA.
 *
 * Auto-generated by scripts/lib/discover-programs.ts. Each entry maps a
 * college slug to the catalog platform discovered for that college. Edit
 * configs (catoid, catalogYear, programNavoids, etc.) per the platform
 * template's options interface before relying on the data.
 *
 * Usage:
 *   npx tsx scripts/la/scrape-programs.ts
 */

import * as fs from "fs";
import * as path from "path";
import { applyProgramMatching } from "../../lib/programs/matcher.js";
import { scrapeCourseleafPrograms } from "../lib/scrape-courseleaf-programs.js";
import { scrapeAcalogPrograms } from "../lib/scrape-acalog-programs.js";

async function run(
  slug: string,
  scrape: () => Promise<{ programs: unknown[]; catalog_year: string; catalog_url: string; college_slug: string; scraped_at: string }>,
): Promise<void> {
  console.log(`\n=== ${slug} ===`);
  try {
    const data = await scrape();
    if (data.programs.length === 0) {
      console.log(`  No programs found for ${slug}.`);
      return;
    }
    const { matched, unmatched } = applyProgramMatching(data.programs as never);
    console.log(`  Matcher: ${matched} matched / ${unmatched} unmatched`);
    const outDir = path.join(process.cwd(), "data", "la", "programs");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(data, null, 2));
    console.log(`  ✓ Wrote ${data.programs.length} programs → ${outPath}`);
  } catch (e) {
    console.error(`  ✗ ${slug} failed: ${e}`);
  }
}

async function main() {
  console.log("LA program scraper");
  // nunez-community-college (courseleaf) — Nunez uses /programs/ not the
  // default /programs-study/.
  await run("nunez-community-college", () =>
    scrapeCourseleafPrograms({ collegeSlug: "nunez-community-college", baseUrl: "https://catalog.nunez.edu", programIndexPath: "/programs/" }),
  );

  // fletcher-technical-community-college (acalog)
  await run("fletcher-technical-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "fletcher-technical-community-college", baseUrl: "https://catalog.fletcher.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true, useSearchDiscovery: true }),
  );

  // south-louisiana-community-college (acalog) — programs listed under
  // navoid=10083 ("Programs"). Probed manually 2026-05-29.
  await run("south-louisiana-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "south-louisiana-community-college", baseUrl: "https://catalog.solacc.edu", catoidFallback: 22, programNavoids: [10083], autoDiscoverCatoid: false }),
  );

  // louisiana-delta-community-college (acalog) — catalog.ladelta.edu is behind
  // AWS WAF JS-challenge; plain fetch returns a 1.9 KB challenge page. Use
  // Playwright so headless Chromium solves the challenge automatically.
  // navoid=46 ("All Programs") has an empty textcontainer in the gateway theme;
  // search_advanced.php works via Playwright and returns poids correctly.
  await run("louisiana-delta-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "louisiana-delta-community-college", baseUrl: "https://catalog.ladelta.edu", catoidFallback: 3, programNavoids: [], autoDiscoverCatoid: false, useSearchDiscovery: true, usePlaywright: true }),
  );

  // baton-rouge-community-college (acalog) — navoid=76 ("Programs A-Z") has
  // 61 preview_program.php links; navoid=85 ("Programs of Study") is a
  // navigation parent with no direct program poids.
  await run("baton-rouge-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "baton-rouge-community-college", baseUrl: "https://catalog.mybrcc.edu", catoidFallback: 3, programNavoids: [76], autoDiscoverCatoid: false }),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
