/**
 * scrape-programs.ts — degree/program requirements for UT.
 *
 * Auto-generated by scripts/lib/discover-programs.ts. Each entry maps a
 * college slug to the catalog platform discovered for that college. Edit
 * configs (catoid, catalogYear, programNavoids, etc.) per the platform
 * template's options interface before relying on the data.
 *
 * Usage:
 *   npx tsx scripts/ut/scrape-programs.ts
 */

import * as fs from "fs";
import * as path from "path";
import { applyProgramMatching } from "../../lib/programs/matcher.js";
import { scrapeAcalogPrograms } from "../lib/scrape-acalog-programs.js";
import { scrapeCourseleafPrograms } from "../lib/scrape-courseleaf-programs.js";

async function run(
  slug: string,
  scrape: () => Promise<{ programs: unknown[]; catalog_year: string; catalog_url: string; college_slug: string; scraped_at: string }>,
): Promise<void> {
  console.log(`\n=== ${slug} ===`);
  try {
    const data = await scrape();
    if (data.programs.length === 0) {
      console.log(`  No programs found for ${slug}.`);
      return;
    }
    const { matched, unmatched } = applyProgramMatching(data.programs as never);
    console.log(`  Matcher: ${matched} matched / ${unmatched} unmatched`);
    const outDir = path.join(process.cwd(), "data", "ut", "programs");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(data, null, 2));
    console.log(`  ✓ Wrote ${data.programs.length} programs → ${outPath}`);
  } catch (e) {
    console.error(`  ✗ ${slug} failed: ${e}`);
  }
}

async function main() {
  console.log("UT program scraper");
  // snow-college (courseleaf)
  //
  // Snow's CourseLeaf catalog uses /programs/ rather than the template
  // default /programs-study/. Verified via curl 2026-05-28:
  //   https://catalog.snow.edu/programs/ → 200 with full degree list.
  await run("snow-college", () =>
    scrapeCourseleafPrograms({
      collegeSlug: "snow-college",
      baseUrl: "https://catalog.snow.edu",
      programIndexPath: "/programs/",
    }),
  );

  // salt-lake-community-college (acalog)
  //
  // The Phase-6 auto-discovery probe missed SLCC's catalog because it
  // tried `salt.edu` (wrong domain — SLCC is `slcc.edu`). Manually
  // verified 2026-05-29 that catalog.slcc.edu is Acalog: the
  // `/preview_program.php` URL redirects to `index.php?catoid=28` and
  // the sidebar exposes nav links `?navoid=9697` (Degrees and
  // Certificates) + `?navoid=9720` (Programs Listed Alphabetically).
  //
  // catoid is pinned to 28 (current catalog as of probe). Auto-discover
  // returned an old archive (catoid=3) whose navoid IDs don't match the
  // ones used by the live current catalog. The navoids 9697 + 9720
  // were sampled from catoid=28's sidebar nav, so they must be paired
  // with that catoid.
  // 9720 is the comprehensive alphabetical index — preferred. 9697 is
  // also included so degree/certificate groupings the alphabetical
  // index sometimes skips are picked up.
  await run("salt-lake-community-college", () =>
    scrapeAcalogPrograms({
      collegeSlug: "salt-lake-community-college",
      baseUrl: "https://catalog.slcc.edu",
      catoidFallback: 28,
      programNavoids: [9720, 9697],
      autoDiscoverCatoid: false,
    }),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
