/**
 * scrape-programs.ts — degree/program requirements for UT.
 *
 * Auto-generated by scripts/lib/discover-programs.ts. Each entry maps a
 * college slug to the catalog platform discovered for that college. Edit
 * configs (catoid, catalogYear, programNavoids, etc.) per the platform
 * template's options interface before relying on the data.
 *
 * Usage:
 *   npx tsx scripts/ut/scrape-programs.ts
 */

import * as fs from "fs";
import * as path from "path";
import { applyProgramMatching } from "../../lib/programs/matcher.js";
import { scrapeCourseleafPrograms } from "../lib/scrape-courseleaf-programs.js";

async function run(
  slug: string,
  scrape: () => Promise<{ programs: unknown[]; catalog_year: string; catalog_url: string; college_slug: string; scraped_at: string }>,
): Promise<void> {
  console.log(`\n=== ${slug} ===`);
  try {
    const data = await scrape();
    if (data.programs.length === 0) {
      console.log(`  No programs found for ${slug}.`);
      return;
    }
    const { matched, unmatched } = applyProgramMatching(data.programs as never);
    console.log(`  Matcher: ${matched} matched / ${unmatched} unmatched`);
    const outDir = path.join(process.cwd(), "data", "ut", "programs");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(data, null, 2));
    console.log(`  ✓ Wrote ${data.programs.length} programs → ${outPath}`);
  } catch (e) {
    console.error(`  ✗ ${slug} failed: ${e}`);
  }
}

async function main() {
  console.log("UT program scraper");
  // snow-college (courseleaf)
  //
  // Snow's CourseLeaf catalog uses /programs/ rather than the template
  // default /programs-study/. Verified via curl 2026-05-28:
  //   https://catalog.snow.edu/programs/ → 200 with full degree list.
  await run("snow-college", () =>
    scrapeCourseleafPrograms({
      collegeSlug: "snow-college",
      baseUrl: "https://catalog.snow.edu",
      programIndexPath: "/programs/",
    }),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
