-- ============================================================
-- Widen courses.college_code and saved_courses.college_code to TEXT
-- Run via Supabase Dashboard → SQL Editor
--
-- ALREADY APPLIED IN PROD on 2026-05-25 via the Supabase MCP tools
-- during the same session that produced this file. This migration
-- file exists so the schema change is recorded in git rather than
-- existing only as an undocumented ad-hoc ALTER.
--
-- Context:
-- - Migration 012 widened `location` to TEXT, assuming that was the
--   field overflowing VARCHAR(50) on KY import. The import still
--   failed with the same `value too long for type character varying(50)`
--   error, because `location` wasn't actually the culprit.
-- - The real overflow was `college_code`, which is the per-row slug
--   (e.g. "southcentral-kentucky-community-and-technical-college" = 53
--   chars). The slug had been silently > 50 chars on every SCKTC
--   batch insert since the row first appeared.
-- - `saved_courses.college_code` had the same VARCHAR(50) ceiling and
--   would have failed the same way the moment a user saved any
--   long-named college's section, so widening both at once.
-- - Discovered via Supabase MCP after the audit's --check-prod flag
--   (PR #566) surfaced the prod-vs-local gap for KY.
--
-- Anyone adding a state from now on can hit this if a college name
-- generates a slug >50 chars. Other already-too-long slugs the
-- registry currently has (so they were never importable until this
-- migration):
--   southcentral-kentucky-community-and-technical-college  (53)
--   southeast-kentucky-community-and-technical-college     (50 — exactly
--     at the edge; depending on Postgres exact byte counting may pass)
--
-- After applying this migration, re-trigger the KY courses import to
-- backfill SCKTC's 1,908 sections (823 FA + 920 SP + 165 SU). Also
-- worth a full --check-prod sweep across all 35 states to see if any
-- other long-slug colleges have been silently dropping rows.
-- ============================================================

ALTER TABLE courses        ALTER COLUMN college_code TYPE TEXT;
ALTER TABLE saved_courses  ALTER COLUMN college_code TYPE TEXT;
