/**
 * scrape-programs.ts — degree/program requirements for MN.
 *
 * Auto-generated by scripts/lib/discover-programs.ts. Each entry maps a
 * college slug to the catalog platform discovered for that college. Edit
 * configs (catoid, catalogYear, programNavoids, etc.) per the platform
 * template's options interface before relying on the data.
 *
 * Usage:
 *   npx tsx scripts/mn/scrape-programs.ts
 */

import * as fs from "fs";
import * as path from "path";
import { applyProgramMatching } from "../../lib/programs/matcher.js";
import { scrapeAcalogPrograms } from "../lib/scrape-acalog-programs.js";
import { scrapeSmartCatalogIqPrograms } from "../lib/scrape-smartcatalogiq-programs.js";

async function run(
  slug: string,
  scrape: () => Promise<{ programs: unknown[]; catalog_year: string; catalog_url: string; college_slug: string; scraped_at: string }>,
): Promise<void> {
  console.log(`\n=== ${slug} ===`);
  try {
    const data = await scrape();
    if (data.programs.length === 0) {
      console.log(`  No programs found for ${slug}.`);
      return;
    }
    const { matched, unmatched } = applyProgramMatching(data.programs as never);
    console.log(`  Matcher: ${matched} matched / ${unmatched} unmatched`);
    const outDir = path.join(process.cwd(), "data", "mn", "programs");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(data, null, 2));
    console.log(`  ✓ Wrote ${data.programs.length} programs → ${outPath}`);
  } catch (e) {
    console.error(`  ✗ ${slug} failed: ${e}`);
  }
}

async function main() {
  console.log("MN program scraper");
  // south-central-college (acalog)
  await run("south-central-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "south-central-college", baseUrl: "https://catalog.south.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // northland-community-and-technical-college (acalog)
  await run("northland-community-and-technical-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "northland-community-and-technical-college", baseUrl: "https://catalog.northland.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // century-college (acalog)
  await run("century-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "century-college", baseUrl: "https://catalog.century.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // normandale-community-college (smartcatalogiq)
  await run("normandale-community-college", () =>
    scrapeSmartCatalogIqPrograms({ collegeSlug: "normandale-community-college", baseUrl: "https://www.normandale.edu" }),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
