/**
 * scrape-programs.ts — degree/program requirements for NV.
 *
 * Auto-generated by scripts/lib/discover-programs.ts. Each entry maps a
 * college slug to the catalog platform discovered for that college. Edit
 * configs (catoid, catalogYear, programNavoids, etc.) per the platform
 * template's options interface before relying on the data.
 *
 * Usage:
 *   npx tsx scripts/nv/scrape-programs.ts
 */

import * as fs from "fs";
import * as path from "path";
import { applyProgramMatching } from "../../lib/programs/matcher.js";
import {
  scrapeAcalogPrograms,
  discoverProgramNavoids,
} from "../lib/scrape-acalog-programs.js";
import { scrapeCourseleafPrograms } from "../lib/scrape-courseleaf-programs.js";
import { scrapeCoursedogPrograms } from "../lib/scrape-coursedog-programs.js";

// CSN's Acalog catalog: current catalog is catoid=23 but the in-catalog
// "Programs" tab links to catoid=19 navoid=6691, which hosts ~300 program
// pages. Navoid auto-discovery doesn't find this because the current
// catalog's nav page doesn't expose program-listing navoids directly.
const CSN_BASE = "https://catalog.csn.edu";
const CSN_CATOID = 19;
const CSN_NAVOIDS = [6691];

// TMCC's Courseleaf catalog uses /degrees-certificates/ rather than the
// /programs-study/ default. Note: the Courseleaf template currently
// parses 0 awards from TMCC's pages (different HTML structure) —
// leaving it wired so the index discovery proves the path is correct;
// award extraction needs template work to recognize TMCC's layout.
const TMCC_BASE = "https://catalog.tmcc.edu";

async function run(
  slug: string,
  scrape: () => Promise<{ programs: unknown[]; catalog_year: string; catalog_url: string; college_slug: string; scraped_at: string }>,
): Promise<void> {
  console.log(`\n=== ${slug} ===`);
  try {
    const data = await scrape();
    if (data.programs.length === 0) {
      console.log(`  No programs found for ${slug}.`);
      return;
    }
    const { matched, unmatched } = applyProgramMatching(data.programs as never);
    console.log(`  Matcher: ${matched} matched / ${unmatched} unmatched`);
    const outDir = path.join(process.cwd(), "data", "nv", "programs");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(data, null, 2));
    console.log(`  ✓ Wrote ${data.programs.length} programs → ${outPath}`);
  } catch (e) {
    console.error(`  ✗ ${slug} failed: ${e}`);
  }
}

async function main() {
  console.log("NV program scraper");

  // college-of-southern-nevada (acalog) — hard-coded navoid (see header comment)
  await run("college-of-southern-nevada", () =>
    scrapeAcalogPrograms({
      collegeSlug: "college-of-southern-nevada",
      baseUrl: CSN_BASE,
      catoidFallback: CSN_CATOID,
      programNavoids: CSN_NAVOIDS,
      autoDiscoverCatoid: false,
    }),
  );

  // truckee-meadows-community-college (courseleaf)
  await run("truckee-meadows-community-college", () =>
    scrapeCourseleafPrograms({
      collegeSlug: "truckee-meadows-community-college",
      baseUrl: TMCC_BASE,
      programIndexPath: "/degrees-certificates/",
    }),
  );

  // western-nevada-college (coursedog)
  await run("western-nevada-college", () =>
    scrapeCoursedogPrograms({
      collegeSlug: "western-nevada-college",
      catalogDomain: "catalog.wnc.edu",
      catalogYear: "2025-2026",
    }),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
