/**
 * scrape-programs.ts — degree/program requirements for CO.
 *
 * Auto-generated by scripts/lib/discover-programs.ts. Each entry maps a
 * college slug to the catalog platform discovered for that college. Edit
 * configs (catoid, catalogYear, programNavoids, etc.) per the platform
 * template's options interface before relying on the data.
 *
 * Usage:
 *   npx tsx scripts/co/scrape-programs.ts
 */

import * as fs from "fs";
import * as path from "path";
import { applyProgramMatching } from "../../lib/programs/matcher.js";
import { scrapeAcalogPrograms } from "../lib/scrape-acalog-programs.js";
import { scrapeCourseleafPrograms } from "../lib/scrape-courseleaf-programs.js";

async function run(
  slug: string,
  scrape: () => Promise<{ programs: unknown[]; catalog_year: string; catalog_url: string; college_slug: string; scraped_at: string }>,
): Promise<void> {
  console.log(`\n=== ${slug} ===`);
  try {
    const data = await scrape();
    if (data.programs.length === 0) {
      console.log(`  No programs found for ${slug}.`);
      return;
    }
    const { matched, unmatched } = applyProgramMatching(data.programs as never);
    console.log(`  Matcher: ${matched} matched / ${unmatched} unmatched`);
    const outDir = path.join(process.cwd(), "data", "co", "programs");
    fs.mkdirSync(outDir, { recursive: true });
    const outPath = path.join(outDir, `${slug}.json`);
    fs.writeFileSync(outPath, JSON.stringify(data, null, 2));
    console.log(`  ✓ Wrote ${data.programs.length} programs → ${outPath}`);
  } catch (e) {
    console.error(`  ✗ ${slug} failed: ${e}`);
  }
}

async function main() {
  console.log("CO program scraper");
  // aims-community-college (acalog)
  await run("aims-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "aims-community-college", baseUrl: "https://catalog.aims.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // arapahoe-community-college (acalog)
  await run("arapahoe-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "arapahoe-community-college", baseUrl: "http://catalog.arapahoe.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // morgan-community-college (acalog)
  await run("morgan-community-college", () =>
    scrapeAcalogPrograms({ collegeSlug: "morgan-community-college", baseUrl: "https://catalog.morgan.edu", catoidFallback: 0, programNavoids: [], autoDiscoverCatoid: true }),
  );

  // colorado-mountain-college (courseleaf)
  await run("colorado-mountain-college", () =>
    scrapeCourseleafPrograms({ collegeSlug: "colorado-mountain-college", baseUrl: "https://catalog.colorado.edu" }),
  );

  // colorado-northwestern-community-college (courseleaf)
  await run("colorado-northwestern-community-college", () =>
    scrapeCourseleafPrograms({ collegeSlug: "colorado-northwestern-community-college", baseUrl: "https://catalog.colorado.edu" }),
  );

  // lamar-community-college (courseleaf)
  await run("lamar-community-college", () =>
    scrapeCourseleafPrograms({ collegeSlug: "lamar-community-college", baseUrl: "https://catalog.lamar.edu" }),
  );

  // northeastern-junior-college (courseleaf)
  await run("northeastern-junior-college", () =>
    scrapeCourseleafPrograms({ collegeSlug: "northeastern-junior-college", baseUrl: "https://catalog.northeastern.edu" }),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
